### PR TITLE
inital add of compiler/perl.vim

### PR DESCRIPTION
**Pull request by harleypig**
Here is the initial import of the version found in VIm 7.3, patches 1-35.  This is for #128. Is this what you were looking for?

### CODE REVIEW

**Comment by hoelzro** [comment]
@petdance Did you ever get a hold of the original maintainer for this file?

**Comment by petdance** [comment]
No, I didn't.  I don't remember this ticket at all.

**Comment by hoelzro** [comment]
I think we can just merge this, to be honest; since it's been included in the official Vim distribution, doesn't it fall under Vim's licensing?

**Comment by hoelzro** [comment]
I believe if we use the Vim license (as referenced in #196), we are able to simply include this file.

**Comment by dkearns** [comment]
I have some Perl related compiler plugins.  I was going to just send them to Bram but if you want them included here I can do that at the same time.

I'd prefer they weren't _just_ here though as having to run around Github trying to find runtime files is a bit of a pet hate of mine. :)

**Comment by petdance** [comment]
If they're universally usable, I think this would be the place.   New PR, please.

It would also give us reason to sync up w/Bram again.

**Comment by petdance** [comment]
I'm closing this since we have #305 now.

**Pull request closed without merging**
