### PR TITLE
Add Test::More keywords

### PR DESCRIPTION
**Pull request by egawata**
Add `new_ok` and `done_testing` of `Test::More` to `contrib/test-more.vim` to be highlighted.

### CODE REVIEW

**Comment by oalders** [comment]
I don't think the test failure is related to the content of this PR.

**Comment by egawata** [comment]
@oalders 
Yes, that's probably related to #281, and the problem has already been solved.
Rerunning CI would pass.

**Comment by oalders** [comment]
Just tested this out and it works for me. 👍 Any reason not to merge it? It's a pretty simple change.

**Comment by oalders** [comment]
Thanks for merging this @petdance and thanks for the PR @egawata! I see that the build failed. I'm wondering if https://github.com/vim-perl/vim-perl/pull/284 would be helpful there. I made some changes to how the tests are run and the builds are passing there. I will pull in this change and force-push to ensure that that PR is still correct.

Or, if you want to use GitHub Actions instead, I could whip something up for that. It tends to be faster than Travis.

**Comment by oalders** [comment]
Oh, I misunderstood. The commit above says that 1 check failed, but the commit in the `dev` branch says that the check passed. So, the build is still green. :)

**Pull request merged**
