### PR TITLE
perl 5.28 fixes

### PR DESCRIPTION
**Pull request by zdm**

### CODE REVIEW

**Comment by hoelzro** [comment]
@zdm Thanks for taking a look at this; unfortunately, your change causes numerous highlighting and folding failures.  I'm going to take a look at this issue today and hopefully fix it.

**Comment by zdm** [comment]
@hoelzro This is because I removed perlSubPrototypeError and perlSubError highlight.
They did regexps complex and I think, that syntax script should only highlight recognized syntax constructions, but not try to find errors.
If you agree with this - you just need to update tests.

**Comment by hoelzro** [comment]
I'm not sure how I feel about highlighting errors, but vim-perl users may have become accustomed to that behavior by now, so I'm not keen on removing it.

**Comment by zdm** [comment]
Ok.
Pls, also look at the line 170.
It fixes the issue #220

**Pull request closed without merging**
