### PR TITLE
Simplify DATA section matching

### PR DESCRIPTION
**Pull request by dkearns**
- Simplify perlDATA region end patterns.
- Add perlDATAStart syntax group to match __DATA__ and __END__

### CODE REVIEW

**Comment by dkearns** [comment]
https://github.com/vim-perl/vim-perl/pull/296/commits/7466dfaf5523b49b687551a438100b11724bbecb is causing the current folding test failures in 06_corpus.t.

Apparently Vim doesn't wish to include a match for the syn-region end pattern in the fold if it's empty.

So `__DATA__` followed by a single empty line doesn't fold at all.  See the DATA section in [Point.pm](https://github.com/vim-perl/vim-perl/blob/p5-corpus/corpus/Moose-2.1005/benchmarks/cmop/lib/Plain/Point.pm) for an example.

The same problem actually occurs for empty-string delimited heredocs so the following doesn't fold either.

```perl
print <<'';

# empty line above terminates heredoc
```

For the DATA region a kludgy solution appears to be using an end pattern that can 'never' match causing the region to run to the end of the file.  This has the possibly surprising benefit of being about 5 times as fast as `\%$` and ~~eleventy billion~~ 50 times as fast as the original implementation.

This, obviously, won't help with the heredoc though.

FWIW, I apparently changed the Ruby implementation to use the end of file pattern `\%$` almost twenty years ago and no one has complained and the bug, or quirk, has been there since the initial release of folding over twenty years ago.

So we can:

1. live with it and update the tests until such time as it's addressed in Vim
2. use a funky `HIDE_AND_SEEK_WITH_VIM` end delimiter instead of `\%$`,  leaving the tests alone,  and having the feature work properly for DATA regions  but not for heredocs
3. revert to the original slow implementation

**Comment by petdance** [comment]
I think "revert to the original" is the way to go, unless "slow" means "makes all of syntax highlighting slow".

**Comment by dkearns** [comment]
I think that's the worst option and included it mostly for completeness.  The original implementation is pathological, matching everything as the end pattern then skipping it.  I was initially motivated to change it because it was slow.

There's a couple of issue reports and/or mailing list messages related to large data regions slowing everything down. E.g., https://github.com/vim-perl/vim-perl/issues/131

From a user perspective I could take either of the other two.  Sometimes having a single blank line under the DATA section fold is pretty much a non-issue as far as I can tell.  I ran through the repo and had to double check whether it was even there.  I guess if you habitually `Gzo` to open that fold you might get annoyed by having to sometimes bump yourself up a line to the fold though I seem to do that without thinking.

I'd probably be inclined to go with option two.  The behaviour is correct and the performance is improved.  It'd also be nice to put a runaway region to good use after all the pain they've caused me over the years.

**Comment by petdance** [comment]
> unless "slow" means "makes all of syntax highlighting slow".

I think that covers what you're saying, so I agree, let's do "use a funky HIDE_AND_SEEK_WITH_VIM end delimiter instead of \%$".  New PR, please, that we can point to from here.

**Pull request merged**
