### PR TITLE
perl 5.28 sub fixes

### PR DESCRIPTION
**Pull request by zdm**
Fix for sub hl and fold.

### CODE REVIEW

**Comment by hoelzro** [comment]
@zdm Thanks for sending this in - your change seems to fail the "folding subs with ; in the prototype" test.  I'll see if I can work on top of your fix to get that to pass!

In the future, could you please run the tests and try to get them to pass?  If you need help with that, please let me know and I'll guide you through it and/or improve the documentation!

In addition, please try to use more descriptive commit messages; vim syntax files are kind of hard to understand, and the same applies to their diffs!  Having commit messages explaining the problem they're fixing and why the fix is done a certain way goes a long way into making the project easier to work with!

Also, if you plan on contributing multiple unrelated fixes (for example, fixes for highlighting and `perl_fold_do_blocks`), please open separate PRs for each of them.

**Comment by zdm** [comment]
Hmm, I ran the tests before made commit.

**Comment by hoelzro** [comment]
@zdm Did the tests warn you about uninstalled modules?  I have a feeling that the tests succeed if you don't have all the modules you need, which is definitely _not_ what I should have done!

**Comment by zdm** [comment]
Test for sub with ";" in prototype is not passed.
I will fix it now.

**Comment by zdm** [comment]
@hoelzro done, all tests are passed, everything works

**Comment by hoelzro** [comment]
Thanks @zdm - I really appreciate the extra effort on your part!  I'll look over these changes.

**Comment by hoelzro** [comment]
Nice job on that fix @zdm! Merging

**Comment by zdm** [comment]
Thank you.

**Pull request merged**
