### PR TITLE
Set b:undo_indent

### PR DESCRIPTION
**Pull request by dkearns**
See :help undo_indent for details.

### CODE REVIEW

**Comment by petdance** [comment]
Please say more about what this will do.  Is it currently doing something wrong that this will fix?

**Comment by dkearns** [comment]
In short, the options set in the indent script aren't being restored when the filetype is changed.  

Every indent script should set this variable to clean up after itself. `b:undo_indent` is to indent/perl.vim as `b:undo_ftplugin` is to ftplugin/perl.vim.  You're already setting `b:undo_ftplugin` correctly in the ftplugin.

If `:help undo_indent` is unclear maybe it can be improved?

**Comment by petdance** [comment]
No, it's fine. I didn't know if this was just a "You should do this because it's best practice" or if there was a specific problem that it was causing.

**Comment by petdance** [comment]
It's not clear to me how exactly you decided what should be set in that line.  However, since I see that you've done vim for years, and you're not some fly-by-night file patcher, I trust you.

Thank you.

**Comment by dkearns** [comment]
Well, it leaves `indentexpr` and `indentkeys` set to the Perl values after a filetype change of the current buffer for filetypes that don't set these themselves.

E.g., a filetype that just sets `cinkeys` for its indenting will get some unexpected Perl indenting embellishments after a filetype change.

**Comment by dkearns** [comment]
> It's not clear to me how exactly you decided what should be set in that line. 

Any options, mappings, commands and similar set in the script should be 'restored' and those were the only two options the script sets.  The `indentexpr` functions tend to be left around as they're essentially namespaced.

If it's not clear, those are just the option's short form names.  It's sort of the prevailing style convention to use the short form in the undo variable settings.  I can change it to use the full forms if you like.

I just noticed there's the `b:indent_use_syntax` variable that should probably be deleted via the undo mechanism too or, if it's not needed outside the indent plugin, it could be changed to a script-local variable.  I'll offer up a PR tomorrow.

> However, since I see that you've done vim for years, and you're not some fly-by-night file patcher, I trust you.

Well that might be the nicest thing someone has said about me in some time I'm not sure I'd advise that approach.

**Pull request merged**
