### PR TITLE
fold_block highlighting improvements and new syntax file to support Function::Parameters

### PR DESCRIPTION
**Pull request by chumakd**

### CODE REVIEW

**Comment by hoelzro** [comment]
@chumakd This looks good, thanks for sending this our way.  Quick question about 5fb3987eb: was `foreach` not being properly detected?

**Comment by hoelzro** [comment]
@chumakd Any thoughts on my question?

**Comment by chumakd** [comment]
Sorry, I somehow missed your post.. And should have written a proper commit msg with a better explanation of the change, in the first place.
The point of that patch ( 5fb3987 ) is that it enables _perlBlockFold_ for a code like

    for my $i (@list) {
    }

Original version supports it only for the `foreach`, but not `for`.

**Comment by hoelzro** [comment]
@chumakd Thanks for filling me in, and for submitting the code!

**Pull request merged**
