### PR TITLE
Add missing pragmas

### PR DESCRIPTION
**Pull request by dkearns**
That pattern is doing a lot of alternation.  I'd think using keywords and nextgroup would improve performance.

`:syntime` tells me it's usually the second worst performing pattern.

### CODE REVIEW

**Comment by petdance** [comment]
We can't use keywords because it breaks the highlighting of autoquoted words to the left of fat commas.  I should put a note in there somewhere explaining this.

**Comment by dkearns** [comment]
It shouldn't do if we contain them to the `nextgroup` of `use`.

Something like:

```vim
syn keyword perlPragma strict warnings contained
syn match perlStatementInclude "\<use\>" nextgroup=perlPragma skipwhite
```

**Comment by petdance** [comment]
If you can figure out a way to do it, then I'd be all ears (in a different PR.)

The simplest test case is basically

```
my %foo = (
    return => 1,
    ref => 2,
    sub => 3,
);
```

**Comment by petdance** [comment]
I'm sorry, I just realized you were talking about just using keywords for `use`, not changing everything to use keywords.

**Comment by petdance** [comment]
This change breaks t_source/perl/issue166.t.  I should have tested it before doing the merge. :-/ Can I get a fix for this, please, on a separate PR?

**Comment by petdance** [comment]
This change breaks t_source/perl/issue166.t.  I've reverted it.

Looks like it may just need an update to the test, maybe?

Thanks.

**Comment by dkearns** [comment]
Done.  Let me know if you want the commits squashed.

I think I was subconsciously availing myself of the instructions in Contributing to leave it up to you while also forgetting to mention it. ;)

**Comment by petdance** [comment]
Please make a new PR for it.  Thanks.

I'll take care of Contributing.

**Comment by dkearns** [comment]
Along with the reference in CONTRIBUTING there's also instructions in some of the test output to leave test updates to a maintainer.

**Pull request merged**
