### PR TITLE
Add a POD filetype plugin

### LINKED ISSUE #87: matchit support for Pod commands
When in Pod, it would be nice to use matchit's "%" operator to jump to the next Pod command.

### PR DESCRIPTION
**Pull request by dkearns**
Fixes #87.

### CODE REVIEW

**Comment by dkearns** [comment]
@petdance, if you're happy with this could you please merge it?  Thanks.

**Comment by petdance** [comment]
Yes, of course.  I just have many other things I work on as well.  Thanks.

**Comment by dkearns** [comment]
No hurry.

My understanding was that you were generally considering all of my PRs as (WIP) until I asked for them to be merged.

**Comment by petdance** [comment]
Aha, yes, now I understand.  Thanks.

**Pull request merged**
