### PR TITLE
Improve number literal highlighting

### PR DESCRIPTION
**Pull request by dkearns**
- Highlight new octal literal prefix syntax
- Allow uppercase prefixes in binary/hexadecimal/octal literals

Let me know if these commits are too small and should be squashed.  I'm not sure about the prevailing style.

### CODE REVIEW

**Comment by dkearns** [comment]
We could also just use `syn case ignore` around the whole number section?

**Comment by petdance** [comment]
I don't know. You know syntax highlighting better than I do, but I think that the smaller the change to be made, the better. All of this is just so brittle.

**Comment by dkearns** [comment]
OK, there's a few edge-case bugs in the number literal highlighting.  So leave this PR open and I'll add to it when I get a chance over the next week or so.

Thanks,
Doug

**Comment by dkearns** [comment]
So sanity has prevailed and some of the 'interesting' edge cases are now invalid in recent versions so I won't bother with them.

I'm assuming the principle for this project's syntax highlighting is that anything valid should be highlighted?

What about things like misuse of `_` in number literals (E.g. `1__2__3__`) that are only flagged with a warning?  Is it worth adding optional error highlighting or does that just annoy everyone for no real gain?  I've never been sure, myself.

**Comment by petdance** [comment]
I don't see value in accomodating `1__2__3__`

**Comment by petdance** [comment]
Will this introduce incompatibilities with vim 7.x?  Do older vims have `\d`?

**Comment by dkearns** [comment]
No, \d and, similar classes, were introduced in Vim 6 and they're already being used in the file.  They always have been, even in those number literal patterns. :) 

The `[:digit:]` style character classes were required as the `\d` style can't be used in a `[..]` collection.

**Comment by petdance** [comment]
OK, so is this PR ready to merge?

**Comment by dkearns** [comment]
Yes please.

I'm also running tests against the whole 'standard' distribution and noticed that octal and binary floating point are mostly supported and tested (a bit sloppy in what they allow) but I couldn't find any reference to them actually be a supported feature so I didn't add them.

Comments in the lexer suggest that they were accidentally supported and they're not sure what to do with them but there's some ML messages that confuse matters further. 

Sometimes it doesn't hurt get out ahead of these changes but this seemed a step too far.

**Pull request merged**
