### PR TITLE
Improve heredoc highlighting

### PR DESCRIPTION
**Pull request by dkearns**
I have some other heredoc improvements and, maybe, bug fixes to come but I might not get to them for a week or so.

If you prefer, leave this open and I can continue adding to this PR.

### CODE REVIEW

**Comment by petdance** [comment]
As long as they're all heredoc-related, then yeah dump 'em here please.

**Comment by dkearns** [comment]
What's the short story on contrib/?  Am I supposed to be updating that as well or is that for other contributors, if you will, to maintain?

Some of it doesn't look fully cooked.

**Comment by petdance** [comment]
I'd lean towards leaving them be.

**Comment by dkearns** [comment]
This is ready to merge if you're happy with it.

**Pull request merged**
